# Generated by Django 2.1.1 on 2018-09-24 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=2000)),
                ('short_code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
