# Generated by Django 2.1.1 on 2018-09-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180924_1035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('long_url', 'short_code')},
        ),
    ]
