# Generated by Django 2.1.1 on 2018-09-24 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180924_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
